INSERT INTO CURSO VALUES
('ADMINISTRAÇÃO')
INSERT INTO CURSO VALUES
('ANÁLISE E DESENVOLVIMENTO DE SISTEMAS')
INSERT INTO CURSO VALUES
('ANÁLISE E DESENVOLVIMENTO DE SISTEMAS EAD')
INSERT INTO CURSO VALUES
('BANCO DE DADOS')
INSERT INTO CURSO VALUES
('ENGENHARIA DA COMPUTAÇÃO')
INSERT INTO CURSO VALUES
('GESTÃO DA TECNOLOGIA DA INFORMAÇÃO')
INSERT INTO CURSO VALUES
('JOGOS DIGITAIS')
INSERT INTO CURSO VALUES
('PROCESSOS GENRENCIAIS')
INSERT INTO CURSO VALUES
('PRODUÇÃO MULTIMÍDIA')
INSERT INTO CURSO VALUES
('REDE DE COMPUTADORES')
INSERT INTO CURSO VALUES
('SISTEMAS DE INFORMAÇÃO')
