INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(1, 'ALAN ALVES DE OLIVEIRA', 'aa_oliveira@impacta.com.br','11987654321','ALAN')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(2, 'ALBERTO DE MEDEIROS JUNIOR', 'am_junior@impacta.com.br','11987658547','ALBERTO')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(3, 'ALEXANDRE LEITE RANGEL', 'al_rangel@impacta.com.br','11987657596','RANGEL')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(4, 'ALEXANDRE LOCCI MARTINS', 'al_martins@impacta.com.br','11945698521','MARTINS')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(5, 'ALVARO TOSHIO TAKEI', 'at_takei@impacta.com.br','11941856721','ALVARO')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(6, 'ANA CRISTINA DOS SANTOS', 'ac_santos@impacta.com.br','11987456325','ANA')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(7, 'BRUNO ROBERTO KALKEVICIUS', 'br_kalkevicius@impacta.com.br','11974125896','BRUNO')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(8, 'CEZAR BELLINI', 'c_bellini@impacta.com.br','11996587413','CEZAR')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(9, 'EDSON BENITES SILVA', 'eb_silva@impacta.com.br','11987654322','EDSON')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(10, 'EDSON TIHARU TSUKIMOTO', 'et_tsukimoto@impacta.com.br','11987654313','TSUKIMOTO')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(11, 'EDUARDO LUIS DE QUEIROZ', 'el_queiroz@impacta.com.br','11966454321','EDU')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(12, 'EMILIO MURTA RESENDE', 'em_resende@impacta.com.br','11987458210','EMILIO')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(13, 'FELIPE AUGUSTO ROCHA DIAS', 'fa_dias@impacta.com.br','11971218326','FELIPE')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(14, 'FERNANDO ZUHER', 'f_zuher@impacta.com.br','11999590830','FERNANDO')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(15, 'FRANCESCA ROMANELLI', 'f_romanelli@impacta.com.br','11992280220','FRANCESCA')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(16, 'GISELDA FERNANDA PEREIRA', 'gf_pereira@impacta.com.br','11995908380','GISELDA')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(17, 'GUILHERME GARCEZ LOHMANN', 'gg_lohmann@impacta.com.br','11968420838','GUILHERME')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(18, 'GUSTAVO MENDES FERREIRA', 'gm_ferreira@impacta.com.br','11922015762','FERREIRA')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(19, 'ILANA DE ALMEIDA SOUZA CONCILIO', 'ia_concilio@impacta.com.br','11936750052','ILANA')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(20, 'IZA MELÃO', 'i_melão@impacta.com.br','11922982427','IZA')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(21, 'JOÃO PAULO VENÂNCIO COUTINHO', 'jp_coutinho@impacta.com.br','11929590820','JP')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(22, 'JOSÉ PACHECO DE ALMEIDA PRADO', 'jp_prado@impacta.com.br','11936425128','PACHECO')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(23, 'LEONARDO MASSAYUKI TAKUNO', 'lm_takuno@impacta.com.br','11912312345','TAKUNO')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(24, 'LUCAS MENDES MARQUES GONÇALVES', 'lm_gonçalves@impacta.com.br','11999494205','LUCAS')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(25, 'LUCIANO CROCCO', 'l_crocco@impacta.com.br','11994942585','LUCIANO')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(26, 'MARCEL GINOTTI PIRES', 'mg_pires@impacta.com.br','11957079728','MARCEL')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(27, 'MARCELO CORREIA DA SILVA', 'mc_silva@impacta.com.br','11957780780','MARCELO')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(28, 'MARCELO SANSINI TERRA', 'ms_terra@impacta.com.br','11957185873','SANSINI')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(29, 'MARCO TÚLIO JEUNON', 'mt_jeunon@impacta.com.br','11959443034','MARCO')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(30, 'OSVALDO KOTARO TAKAI', 'ok_takai@impacta.com.br','11979933687','TAKAI')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(31, 'PEDRO FELIPE DO PRADO', 'pf_prado@impacta.com.br','11987654871','PEDRO')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(32, 'PLÍNIO BARBIERI FILHO', 'pb_filho@impacta.com.br','11912345678','PLINIO')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(33, 'RENATO DE SOUZA SANTOS', 'rs_santos@impacta.com.br','11910111213','RENATO')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(34, 'RODRIGO PIASSI', 'r_piassi@impacta.com.br','11949754294','RODRIGO')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(35, 'SÉRGIO EDUARDO DI SANTORO BRUZETTI', 'se_bruzetti@impacta.com.br','11993405277','SÉRGIO')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(36, 'VANDERSON GOMES BOSSI', 'vg_bossi@impacta.com.br','11984293066','VANDERSON')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(37, 'VICTOR INÁCIO DE OLIVEIRA', 'vi_oliveira@impacta.com.br','11957985085','VICTOR')
INSERT INTO PROFESSOR (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES
(38, 'VLADIMIR CHAGAS', 'v_chagas@impacta.com.br','11959984087','VLADIMIR')
