INSERT INTO SOLICITACAOMATRICULA
(IDALUNO, IDOFERTADA, DTSOLICITACAO, STATUS)
VALUES
(1,1, GETDATE(),'SOLICITADA'),
(2,1, GETDATE(),'SOLICITADA'),
(3,1, GETDATE(),'SOLICITADA'),
(4,1, GETDATE(),'SOLICITADA'),
(5,1, GETDATE(),'SOLICITADA'),
(6,1, GETDATE(),'SOLICITADA'),
(7,1, GETDATE(),'SOLICITADA'),
(8,1, GETDATE(),'SOLICITADA'),
(9,1, GETDATE(),'SOLICITADA'),
(10,1, GETDATE(),'SOLICITADA'),
(1,1, GETDATE(),'APROVADA'),
(2,1, GETDATE(),'APROVADA'),
(3,1, GETDATE(),'APROVADA'),
(4,1, GETDATE(),'APROVADA'),
(5,1, GETDATE(),'APROVADA'),
(6,1, GETDATE(),'APROVADA'),
(7,1, GETDATE(),'APROVADA'),
(8,1, GETDATE(),'APROVADA'),
(9,1, GETDATE(),'APROVADA'),
(10,1, GETDATE(),'APROVADA'),
(40,1, GETDATE(),'REJEITADA'),
(41,1, GETDATE(),'REJEITADA'),
(42,1, GETDATE(),'REJEITADA'),
(43,1, GETDATE(),'REJEITADA'),
(44,1, GETDATE(),'REJEITADA'),
(45,1, GETDATE(),'REJEITADA'),
(46,1, GETDATE(),'REJEITADA'),
(47,1, GETDATE(),'REJEITADA'),
(48,1, GETDATE(),'REJEITADA'),
(49,1, GETDATE(),'REJEITADA'),
(20,1, GETDATE(),'CANCELADA'),
(21,1, GETDATE(),'CANCELADA'),
(22,1, GETDATE(),'CANCELADA'),
(23,1, GETDATE(),'CANCELADA'),
(24,1, GETDATE(),'CANCELADA'),
(25,1, GETDATE(),'CANCELADA'),
(26,1, GETDATE(),'CANCELADA'),
(27,1, GETDATE(),'CANCELADA'),
(28,1, GETDATE(),'CANCELADA'),
(29,1, GETDATE(),'CANCELADA')

INSERT INTO MENSAGEM 
(IDALUNO, IDPROFESSOR, ASSUNTO, REFERENCIA, CONTEUDO, STATUS, DTENVIO)
VALUES
(1,1,'AC','ATIVIDADE CONTINUA','PROFESSOR, QUAL ASSUNTO DA PROXIMA AC?','ENVIADO',GETDATE()),
(2,2,'AC','ATIVIDADE CONTINUA','PROFESSOR, QUAL ASSUNTO DA PROXIMA AC?','ENVIADO',GETDATE()),
(3,3,'AC','ATIVIDADE CONTINUA','PROFESSOR, QUAL ASSUNTO DA PROXIMA AC?','ENVIADO',GETDATE()),
(4,4,'AC','ATIVIDADE CONTINUA','PROFESSOR, QUAL ASSUNTO DA PROXIMA AC?','ENVIADO',GETDATE()),
(5,5,'AC','ATIVIDADE CONTINUA','PROFESSOR, QUAL ASSUNTO DA PROXIMA AC?','ENVIADO',GETDATE()),
(6,6,'AC','ATIVIDADE CONTINUA','PROFESSOR, QUAL ASSUNTO DA PROXIMA AC?','ENVIADO',GETDATE()),
(7,7,'AC','ATIVIDADE CONTINUA','PROFESSOR, QUAL ASSUNTO DA PROXIMA AC?','ENVIADO',GETDATE()),
(8,8,'AC','ATIVIDADE CONTINUA','PROFESSOR, QUAL ASSUNTO DA PROXIMA AC?','ENVIADO',GETDATE()),
(9,9,'AC','ATIVIDADE CONTINUA','PROFESSOR, QUAL ASSUNTO DA PROXIMA AC?','ENVIADO',GETDATE()),
(10,10,'AC','ATIVIDADE CONTINUA','PROFESSOR, QUAL ASSUNTO DA PROXIMA AC?','ENVIADO',GETDATE()),
(1,1,'AC','ATIVIDADE CONTINUA','PROFESSOR, QUAL ASSUNTO DA PROXIMA AC?','LIDO',GETDATE()),
(2,2,'AC','ATIVIDADE CONTINUA','PROFESSOR, QUAL ASSUNTO DA PROXIMA AC?','LIDO',GETDATE()),
(3,3,'AC','ATIVIDADE CONTINUA','PROFESSOR, QUAL ASSUNTO DA PROXIMA AC?','LIDO',GETDATE()),
(4,4,'AC','ATIVIDADE CONTINUA','PROFESSOR, QUAL ASSUNTO DA PROXIMA AC?','LIDO',GETDATE()),
(5,5,'AC','ATIVIDADE CONTINUA','PROFESSOR, QUAL ASSUNTO DA PROXIMA AC?','LIDO',GETDATE()),
(6,6,'AC','ATIVIDADE CONTINUA','PROFESSOR, QUAL ASSUNTO DA PROXIMA AC?','LIDO',GETDATE()),
(7,7,'AC','ATIVIDADE CONTINUA','PROFESSOR, QUAL ASSUNTO DA PROXIMA AC?','LIDO',GETDATE()),
(8,8,'AC','ATIVIDADE CONTINUA','PROFESSOR, QUAL ASSUNTO DA PROXIMA AC?','LIDO',GETDATE()),
(9,9,'AC','ATIVIDADE CONTINUA','PROFESSOR, QUAL ASSUNTO DA PROXIMA AC?','LIDO',GETDATE()),
(10,10,'AC','ATIVIDADE CONTINUA','PROFESSOR, QUAL ASSUNTO DA PROXIMA AC?','LIDO',GETDATE()),
(1,1,'AC','ATIVIDADE CONTINUA','SERÁ TODO CONTEUDO DA AULA ANTERIOR','RESPONDIDO',GETDATE()),
(2,2,'AC','ATIVIDADE CONTINUA','SERÁ TODO CONTEUDO DA AULA ANTERIOR','RESPONDIDO',GETDATE()),
(3,3,'AC','ATIVIDADE CONTINUA','SERÁ TODO CONTEUDO DA AULA ANTERIOR','RESPONDIDO',GETDATE()),
(4,4,'AC','ATIVIDADE CONTINUA','SERÁ TODO CONTEUDO DA AULA ANTERIOR','RESPONDIDO',GETDATE()),
(5,5,'AC','ATIVIDADE CONTINUA','SERÁ TODO CONTEUDO DA AULA ANTERIOR','RESPONDIDO',GETDATE()),
(6,6,'AC','ATIVIDADE CONTINUA','SERÁ TODO CONTEUDO DA AULA ANTERIOR','RESPONDIDO',GETDATE()),
(7,7,'AC','ATIVIDADE CONTINUA','SERÁ TODO CONTEUDO DA AULA ANTERIOR','RESPONDIDO',GETDATE()),
(8,8,'AC','ATIVIDADE CONTINUA','SERÁ TODO CONTEUDO DA AULA ANTERIOR','RESPONDIDO',GETDATE()),
(9,9,'AC','ATIVIDADE CONTINUA','SERÁ TODO CONTEUDO DA AULA ANTERIOR','RESPONDIDO',GETDATE()),
(10,10,'AC','ATIVIDADE CONTINUA','SERÁ TODO CONTEUDO DA AULA ANTERIOR','RESPONDIDO',GETDATE())

/* DELETE FROM PROFESSOR WHERE IDUSUARIO = 28;

DELETE FROM ALUNO WHERE IDUSUARIO = 31;

UPDATE USUARIO
SET SENHA = 'GUSTAVO2'
WHERE LOGIN = 'GUSTAVO.FERREIRA';

UPDATE MENSAGEM
SET STATUS = 'LIDO',
	DTRESPOSTA = GETDATE(),
	RESPOSTA = 'BOA NOITE, QUAL É EXATAMENTE SUA DUVIDA NA AC?'
WHERE IDALUNO = 37 AND IDPROFESSOR = 5;

UPDATE ENTREGA
SET STATUS = 'CORRIGIDO',
	DTAVALIACAO = GETDATE(),
	NOTA = 8,
	IDPROFESSOR = 39
WHERE IDALUNO = 37 AND IDPROFESSOR = 5 */